### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by flohwie** [CircuitMess/CircuitMess-Ringo-Arduino-packages#1]
There seems to be a type in the readme:
 https://raw.githubusercontent.com/CircuitMess/CircuitMess-Ringo-Arduino-packages/master/package_CircuitMess_Ringo_index.jsonn. 
Shouldn't that be:
 https://raw.githubusercontent.com/CircuitMess/CircuitMess-Ringo-Arduino-packages/master/package_CircuitMess_Ringo_index.json ?
without the secon n in json?

**Comment by robbie8-bit** [comment]
Hello,

Yes, it was a typo! It's been fixed now. Thank you for noticing this.

Robert
